# Dockerfile.consumer
FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

ENV KAFKA_BOOTSTRAP_SERVERS=broker:9092 \
    KAFKA_TOPIC=market_events

# Entrypoint: Kafka → Snowflake consumer
CMD ["python", "-m", "src.consumer.snowflake_consumer"]
